### ISSUE TITLE
Better AnimatedSprite frame updating

### ISSUE THREAD

**Issue by pixelpicosean** [pixelpicosean/lesser-panda#10]
`AnimatedSprite` is not tagged and cannot be paused as other sub-systems.

**Comment by pixelpicosean** [comment]
New graphics system will be responsable for animation updatings, so this will no longer be a problem.

**Comment by rhinostudios** [comment]
Hey dude
With lesserPanda the new place to go for Dev.
Could u point me in right direction with
Animation code

Can this work for animation
For(i=0, i<W1Height,i++){
W1.scale+0.1; W1.addTo(this.stage); 

For faster just use bigger number like 1
Slower use smaller numbers right?

**Comment by rhinostudios** [comment]
Just asking because old Panda doesnt have your setFPS feature

**Comment by pixelpicosean** [comment]
The `AnimatedSprite` is still updating based on time (even though they are updated in the **fixed** process), so FPS won't affect much.

I just reviewed the code and notice the current implementation does not work properly, will try to fix it soon.

BTW. I don't understand what you want to achieve by that code.

**Comment by rhinostudios** [comment]
Im my post I reference W1 as a sprite. 
Using requestAnimFrame(gameLoop)
which runs at 60fps in pixi.

Will this loop work to grow sprite over time?

**Comment by pixelpicosean** [comment]
You code does work but has a few problems.
1. Sprite does not need to be added every single frame, when it is added it'll just be there. 
2. Only `fixedUpdate` method is affected by `FPS`, `update` is called the same as `requestAnimationFrame`.
3. If you want to animate something, try using `SystemAnime`, which provide `tween` animation support.
4. There's no `stage` anymore since `Gfx` is just a normal system now. Instead you can add `SystemGfx` and create some layers.

### The correct way

``` javascript
// Create a sprite called "w1" somewhere
let w1 = Sprite({
  texture: 'bubble',
  scale: { x: 1, y: 0 },
})
.addTo(this.sysGfx.root);

// Inside a tick method (update/fixedUpdate) of game
fixedUpdate(dt, dtSec) {
  if (w1.scale.y < 1) {
    // Let's increase its height every frame now
    w1.scale.y += 0.1;

    // Here's a better way (which will not be affected by FPS)
    w1.scale.y += 1 * dtSec; // We use a number "1" here, so the scale will increase from 0 to 1 in "1 sec"
  }
}
```

### Better: Tween based solution

``` javascript
// To be able to use "tween", let's add the "SystemAnime" first to a game class
// Import it first
const SystemAnime = require('engine/anime')

// Inside the constructor of a `Game`, add it (so we can use it as `sysAnime`)
this.addSystem(new SystemAnime());

// Create a sprite called "w1" somewhere else
let w1 = Sprite({
  texture: 'bubble',
  scale: { x: 1, y: 0 },
})
.addTo(this.sysGfx.root);

// And animate it now
this.sysAnime.tween(w1.scale)
  .to({ y: 1 }, 1000);
```
