### ISSUE TITLE
Using lpanda CLI

### ISSUE THREAD

**Issue by karneaud** [pixelpicosean/lesser-panda#5]
So I installed and downloaded your tools and project. 

When I ran `lpanda server` I am able to get the server up and running **locally**. but not able to test it on my mobile device

I thought I'd give `browser-sync` a try after `lpanda build` but it seems the build doesn't include the "media" folder

**Comment by pixelpicosean** [comment]
What do you mean by "not able to test on mobile devices"? The server should work if your devices are connecting to the same local network just like the `browser-sync` does.

I just don't have time to work on the assets copy task recently.

**Comment by SkyzohKey** [comment]
`ngrok` is a good choice to share a local server around the web IMHO. :)

**Comment by pixelpicosean** [comment]
Thank you @SkyzohKey , `ngrok` looks awesome :D

**Comment by SkyzohKey** [comment]
I use it every day to showcase mockups/prototypes of work to my clients ;p

**Comment by karneaud** [comment]
@SkyzohKey @pixelpicosean not sure why it wouldn't show up on my mobile device but when i implemented `browser-sync` I didn't have a problem. I'm going to try and implement some gulp integration to make my workflow a bit more streamlined. 

Its currently a toss up between Phaser and LesserPanda at the moment. Have to admit that I was up and running a bit faster with Phaser but will play around with Lesser to see what can be done.

I want to build a 2 player 2D canvas game driven by bi directional interaction between devices. So I'm hoping I can accomplish this easier and more simple with Lesser than with Phaser. I'm not comfortable using Phaser.

**Comment by pixelpicosean** [comment]
@karneaud Can you provide more details? Which OS, Node version, which IP you're using on mobile devices etc.

Seems like that I've been focusing too much on the flexibility, there aren't much convenient features to let you make games faster. Hope the up coming `Behavior` system be a game changer.

Not sure whether it'll be easier and simpler for you to achieve the goal, but you don't like the Phaser, so it may be worth to try it yourself.

**Comment by karneaud** [comment]
@pixelpicosean 

OS = Yosemite 
Node = 5.7.1

when i run `lpanda` everything compiles as expected( exception being media assets) and the server states it started at an ip address( and port to use) of my computer. Yet if I go to that address via my mobile device I am unable to connect. 

As stated before when I run `browser-sync` I do get the to view the project from my device but its obvious   when it comes to reloading there is more to be done as `lpanda` seems to compile. 

I would suggest providing some extra tooling so developers can modify to suit as projects would be more diverse. I will try to dabble a bit more in it and see what I can do

**Comment by pixelpicosean** [comment]
The CLI is just a simple tool powered by webpack and the server is simply a webpack-dev-server instance. Feel free to fork the CLI and make your own tool :smile:

**Comment by pixelpicosean** [comment]
@SkyzohKey API document is out, take a look at [weekly #3](https://github.com/pixelpicosean/lesser-panda/wiki/This-Week-in-LesserPanda-%233) for more details.
