### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by karneaud** [pixelpicosean/lesser-panda#6]
Hello,

How does your framework handle collision detection especially when it comes to non rectangular based objects. That is to say collision detection with transparent pngs and polygon type shapes?

**Comment by pixelpicosean** [comment]
Non-rectangular shapes is called `Polygon` which is enabled by change `physics.solver` config to `SAT`. Then you can create body with polygon shapes by providing multiple vertices:

``` javascript
const body = new physics.Body({
  shape: new physics.Polygon([
    Vector.create(0, 0),
    Vector.create(20, 0),
    Vector.create(30, 20),
    Vector.create(20, 40),
    Vector.create(0, 50),
    Vector.create(-20, 20),
  ]),
});
```

Note there's an issue #3 with SAT collision solver, you need to keep `anchor` of Body as `(0.5, 0.5)` to avoid that problem. While using SAT, you should never change its value.

**Comment by pixelpicosean** [comment]
@karneaud In previous versions `Polygon` shape is not exposed from `physics` module, I've just fixed it and the sample I post above should work now.

And you can also checkout the [samples repo](https://github.com/pixelpicosean/lesser-panda-samples), where I just upload a Tilemap collision sample. Tilemap uses `Polygon` shaped bodies internally.
